# Copyright (C) 2008 John 'Ykstort' Doyle
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.

all:
	$(MAKE) all -C boot
clean:
	$(MAKE) clean -C boot
